plugins:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Layout/EndOfLine:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
